name: Build iOS App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Selecionar Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build app
        run: xcodebuild -scheme SeuApp -sdk iphoneos -configuration Release build

      - name: Exportar IPA
        run: |
          mkdir build
          xcodebuild -exportArchive \
          -archivePath build/SeuApp.xcarchive \
          -exportPath build \
          -exportOptionsPlist ExportOptions.plist
